version: '3.9'
services:
  metabase:
    image: metabase/metabase-enterprise:v1.43.2
    container_name: metabase_full_app_embedding_demo
    hostname: metabase
    volumes: 
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment: 
      - "MB_SITE_URL=http://localhost:3000"
      # - "MB_SESSION_COOKIE_SAMESITE=None"
      - "MB_EMBEDDING_APP_ORIGIN=*"
      - "MB_ENABLE_EMBEDDING=true"
      - "MB_PREMIUM_EMBEDDING_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      - "MB_JWT_ENABLED=true"
      - "MB_JWT_IDENTITY_PROVIDER_URI=http://localhost:8080/api/auth/metabase"
      - "MB_JWT_SHARED_SECRET=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
    networks: 
      - metanet1
  setup_full_app_embedding_demo:
    image: bash:5.1.16
    container_name: setup_full_app_embedding_demo
    volumes:
      - $PWD/setup:/tmp
    networks:
      - metanet1
    depends_on:
      - metabase_full_app_embedding_demo
    command: sh /tmp/metabase-setup.sh metabase:3000
  node_full_app_embedding_demo:
    build: .
    container_name: webapp_full_app_embedding_demo
    hostname: webapp
    ports:
      - 8080:8080
    networks:
      - metanet1
    environment:
      - METABASE_URL=http://localhost:3000
      - PORT=8080
networks: 
  metanet1:
    driver: bridge
